disabled_rules:
  - colon
  - comma
  - identifier_name
  - private_over_fileprivate
  - redundant_optional_initialization
  - statement_position
  - trailing_comma
  - type_name

excluded:
  - ./*/AppDelegate.swift
  - ./*/SceneDelegate.swift
